#!/bin/zsh

# aliases
alias reload=". ~/.config/zsh/.zshrc"

# ls
if type lsd > /dev/null 2>&1; then
  alias ls='lsd'
  alias lt='ls --tree'
elif ls --color=auto > /dev/null 2>&1; then
  alias ls='ls --color=auto' # linux
else
  alias ls='ls -G' # macos
fi
alias l='ls -l'
alias la='ls -lah'

# vim
if type nvim > /dev/null 2>&1; then
  alias vim='nvim'
  alias vi='nvim'
fi

# Git aliases
alias g='git'
alias gl='lazygit'
alias gst='git status'
alias gstw='watch -c -t git status -sb'
alias gd='git diff'
alias gds='git diff --staged'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit -v'
alias gacp='git add --all && git commit -m "$(date)" && git push'
