#!/bin/zsh

export DOTFILES="$HOME/.dotfiles"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

# editor
if type nvim > /dev/null 2>&1; then
export EDITOR="nvim"
export VISUAL="nvim"
else
export EDITOR="vim"
export VISUAL="vim"
fi

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zsh_history" # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file

# less (also used by other programs like "man")
export LESSHISTFILE="$XDG_CONFIG_HOME/less/.lesshst"

# Some Homebrew formulae have executables in "/usr/local/sbin"
export PATH="/usr/local/sbin:$PATH"

# Get rid of dotnet telemetry.
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
