#!/bin/zsh

fpath=($DOTFILES/zsh/plugins $fpath)

# Navigating
setopt AUTO_CD                  # Go to folder path without using cd.
setopt CORRECT                  # Spelling correction

# History settings
setopt HIST_IGNORE_DUPS         # Do not record an event that was just recorded again.
setopt HIST_FIND_NO_DUPS        # Do not display a previously found event.
setopt HIST_SAVE_NO_DUPS        # Do not write a duplicate event to the history file.

# Vi mode
bindkey -v
export KEYTIMEOUT=1

# Change cursor
autoload -Uz cursor_mode; cursor_mode

# spaceship prompt
autoload -U promptinit; promptinit
prompt spaceship

# Keybindings
bindkey '^r' history-incremental-search-backward

source $DOTFILES/zsh/completion
source $DOTFILES/zsh/aliases
