#!/bin/zsh

fpath=($DOTFILES/zsh/plugins $DOTFILES/zsh/plugins/pure $fpath)

# Navigating
setopt AUTO_CD                  # Go to folder path without using cd.
setopt CORRECT                  # Spelling correction

# History settings
setopt HIST_IGNORE_DUPS         # Do not record an event that was just recorded again.
setopt HIST_FIND_NO_DUPS        # Do not display a previously found event.
setopt HIST_SAVE_NO_DUPS        # Do not write a duplicate event to the history file.

# Vi mode
bindkey -v
export KEYTIMEOUT=1

# Change cursor
autoload -Uz cursor_mode; cursor_mode

# Pure prompt
autoload -U promptinit; promptinit
prompt pure

# Keybindings
bindkey '^r' history-incremental-search-backward

source $DOTFILES/zsh/completion
source $DOTFILES/zsh/aliases

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Zoxide
eval "$(zoxide init zsh)"
